/**
 * Copyright (C) 2011 (nick @ objectdefinitions.com)
 *
 * This file is part of JTimeseries.
 *
 * JTimeseries is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JTimeseries is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with JTimeseries.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.od.jtimeseries.ui.selector.table;

import com.od.jtimeseries.context.ContextProperties;
import com.od.jtimeseries.ui.timeseries.UIPropertiesTimeSeries;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by IntelliJ IDEA.
 * User: Nick Ebbutt
 * Date: 24-Feb-2010
 * Time: 17:30:29
 */
public class SummaryStatsTableModel<E extends UIPropertiesTimeSeries> extends DynamicColumnsTableModel<E> {

    private List<String> propertyNamesList = new ArrayList<String>();

    public SummaryStatsTableModel(BeanPerRowModel<E> wrappedModel) {
        super(wrappedModel);
        initialize();
    }

    protected boolean updateRequiresStructureChange(int firstRow, int lastRow) {
        boolean result = false;
        int oldSize = propertyNamesList.size();

        addSummaryColumns(firstRow, lastRow);
        if (propertyNamesList.size() != oldSize) {
            result = true;
        }
        return result;
    }

    protected String doGetColumnDescription(int columnIndex) {
        return "This column is a summary statistic which is generated by the timeseries server";
    }

    private void addSummaryColumns(int firstRow, int lastRow) {
        for ( int row = firstRow; row <= lastRow; row++) {
            E s = getObject(row);
            for ( Object prop : s.getProperties().keySet()) {
                String propertyName = (String) prop;
                if (! propertyNamesList.contains(propertyName)) {
                    if ( ContextProperties.isSummaryStatsProperty(propertyName) &&
                        ContextProperties.getSummaryStatsDataType(propertyName) == ContextProperties.SummaryStatsDataType.DOUBLE) {
                        addSummaryProperty(propertyName);
                    }
                }
            }
        }
    }

    private void addSummaryProperty(String propertyName) {
        propertyNamesList.add(propertyName);
    }

    protected Object getValueForDynamicColumn(int rowIndex, int extraColsIndex) {
        String propertyName = propertyNamesList.get(extraColsIndex);
        String propertyValue = getObject(rowIndex).getProperty(propertyName);
        return propertyValue == null || "?".equals(propertyValue) ? null :
            "NaN".equals(propertyValue) ? null : Double.valueOf(propertyValue);
    }

    protected void doAddDynamicColumn(String columnName) {
        if ( ! propertyNamesList.contains(columnName)) {
            addSummaryProperty(columnName);
            fireTableStructureChanged();
        }
    }

    protected boolean isDynamicColumnInThisModel(String columnName) {
        return ContextProperties.isSummaryStatsProperty(columnName);
    }

    public int getDynamicColumnCount() {
        return propertyNamesList.size();
    }

    protected String getDynamicColumnName(int extraColsIndex) {
        return propertyNamesList.get(extraColsIndex);
    }

    protected Class<?> getDynamicColumnClass(int extraColsIndex) {
        return Double.class;
    }
}
